# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: publish_workflow
run-name: publish workflow

# Allow one concurrent deployment
concurrency:
  group: "publish-workflow"
  cancel-in-progress: true

on:
  push:
    paths:
      - .github/workflows/publish.yml
      - backend/**/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build and push Docker image to GitHub
        id: build-and-push-docker-image-to-github
        # Only run on main
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ github.repository }}-node-mongo-app
          docker-image-context: ./backend

      - name: Prepare configuration files
        # Only run on main
        if: github.ref == 'refs/heads/main'
        shell: bash
        working-directory: ./backend/kubernetes
        env:
          # url is the mongodb deployment on port 27017
          MONGODB_URL: mongodb://mongodb-service:27017
        run: |
          # Set version
          docker_image_tags=(${{ steps.build-and-push-docker-image-to-github.outputs.docker-image-tags }})
          docker_image_sha_tag="${docker_image_tags[1]}"
          yq ".spec.template.spec.containers[0].image = \"$docker_image_sha_tag\"" kube-config.yml > new-kube-config.yml && mv new-kube-config.yml kube-config.stateful.yml

      - name: Deploy on the Kubernetes cluster
        # Only run on main
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/execute-command-on-kubernetes-cluster
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}
          kube-namespace: wine-recommender
          kubectl-context: ./backend/kubernetes
          kubectl-args: |
            apply \
              -f kube-config.yml
