# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: publish_frontend_workflow
run-name: publish_frontend workflow

# Allow one concurrent deployment
concurrency:
  group: "publish-frontend-workflow"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - .github/actions/build-and-push-docker-image-to-github/action.yml
      - .github/workflows/publish_frontend.yml
      - frontend/**/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: frontend/wine-recommender
        run: npm ci

      - name: Build app
        working-directory: frontend/wine-recommender
        env:
          API_URL: https://api-wine-recommender.kube.isc.heia-fr.ch
          # So it does not treat warnings as errors
          CI: false
        run: npm run build

      - name: Build and push Docker image to GitHub
        id: build-and-push-docker-image-to-github
        # Only run on main
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ github.repository }}-webapp
          docker-image-context: ./frontend/wine-recommender

      - name: Prepare configuration files
        # Only run on main
        if: github.ref == 'refs/heads/main'
        shell: bash
        working-directory: ./frontend/wine-recommender/kubernetes
        env:
          API_URL: https://api-wine-recommender.kube.isc.heia-fr.ch
        run: |
          # Set version
          docker_image_tags=(${{ steps.build-and-push-docker-image-to-github.outputs.docker-image-tags }})
          docker_image_sha_tag="${docker_image_tags[1]}"
          yq eval 'select(di == 0).spec.template.spec.containers[0].image = "'$docker_image_sha_tag'"' kube-config.yml > new-kube-config.yml && mv new-kube-config.yml kube-config.yml
          cat kube-config.yml

      - name: Deploy Webapp on the Kubernetes cluster
        # Only run on main
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/execute-command-on-kubernetes-cluster
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}
          kube-namespace: wine-recommender
          kubectl-context: ./frontend/wine-recommender/kubernetes
          kubectl-args: |
            apply \
              -f kube-config.yml
